; ===========================================================================
; Main objects data
; ===========================================================================

		include "Objects/Rings/Rings.asm"
		include "Objects/PathSwap/PathSwap.asm"
		include "Objects/Monitor/Monitor.asm"
		include "Objects/Monitor(Hidden)/Monitor(Hidden).asm"
		include "Objects/Spring/Spring.asm"
		include "Objects/Spikes/Spikes.asm"
		include "Objects/SpinForcer/SpinForcer.asm"
		include "Objects/Invisible Barrier/Invisible Barrier.asm"
		include "Objects/Invisible Hurt Block/Invisible Hurt Block Horizontal.asm"
		include "Objects/Invisible Hurt Block/Invisible HurtBlock Vertical.asm"
		include "Objects/Title Card/Title Card.asm"
		include "Objects/Signpost/Signpost.asm"
		include "Objects/Results/LevelResults.asm"
		include "Objects/Explosion/Boss Explosion.asm"
		include "Objects/Explosion/Explosion.asm"
		include "Objects/Bubbler/Bubbler.asm"
		include "Objects/Count Down/Count Down.asm"
		include "Objects/Water Wave/Water Wave.asm"
		include "Objects/StarPost/StarPost.asm"
		include "Objects/Button/Button.asm"
		include "Objects/Blood Mode/Blood Mode.asm"
		include "Objects/Still Sprites/Still Sprites.asm"
		include "Objects/Dialog/Dialog.asm"
		include "Objects/Smooth Palette/Smooth Palette.asm"
		include "Objects/Ridge/Ridge.asm"
		include "Objects/Universal_AfterImage/Code.asm"
		include "Objects/Secrets/Secrets.asm"

; ===========================================================================
; Levels objects data
; ===========================================================================

                include "Objects/Wolf/Code.asm"
                include "Objects/Grounder/Code.asm"
                include "Objects/Fly/Code.asm"
                include "Objects/Grounder/Spawner.asm"
                include "Objects/Grounder/Brick.asm"
                include "Objects/Ghoul/Code.asm"
                include "Objects/Crow/Code.asm"
		include "Objects/Bat/Code.asm"
		include "Objects/Hellgirl/Amy/Code.asm"
		include "Objects/Hellgirl/Tikal/Code.asm"
		include "Objects/Hellgirl/LoveBullet.asm"
		include "Objects/Hellgirl/LoveBullet2.asm"
                include "Objects/Axe Ghost/Code.asm"
                include "Objects/Phantom/Code.asm"
		include "Objects/Feal/Code.asm"
		include "Objects/Walking Armor/Code.asm"
		include "Objects/Floating Platform/Floating Platform.asm"
		include "Objects/Swinging Platform/Swinging Platform.asm"
		include "Objects/Breakable Wall/Breakable Wall.asm"
		include "Objects/Gravity Switch/GravitySwitch.asm"
		include "Objects/Staircase/Staircase.asm"
		include "Objects/CollapsingStairCase/CollapsingStaircase.asm"
		include "Objects/Bumper/Bumper.asm"
		include "Objects/ChainLink/ChainLink.asm"
		include "Objects/HandLauncher/HandLauncher.asm"
		include "Objects/Water Block/Water Block.asm"
		include "Objects/Water Trigger/Water Trigger.asm"
		include "Objects/MGZ Swinging SpikeBall/MGZ Swinging SpikeBall.asm"
		include "Objects/MGZ Swinging SpikeBall/MGZSwingingBall2.asm"
		include "Objects/MGZ Lava Fall/MGZ Lava Fall.asm"
		include "Objects/MGZ Flame Thrower/MGZ Flame Thrower.asm"
		include "Objects/MGZ Fireball Launcher/MGZ Fireball Launcher.asm"
		include "Objects/MGZ Nut/MGZ Nut.asm"
		include "Objects/Bridge/Bridge.asm"
		include "Objects/Curled Vine/Curled Vine.asm"
		include "Objects/FDZ Fan/FDZ Fan.asm"
		include "Objects/FDZ Shooter/FDZ Shooter.asm"
		include "Objects/Skeleton/Code.asm"
; ===========================================================================
; Bosses objects data
; ===========================================================================

                include "Objects/Bosses/Aim/Aim.asm"
                include "Objects/Bosses/Honey/Code.asm"
		include "Objects/Bosses/Firebrand/Code.asm"
		include "Objects/Bosses/Mecha Sonic/Code.asm"
		include "Objects/Bosses/Mecha Sonic/Code2.asm"
		include "Objects/Bosses/Mecha Sonic/ExplodingBullet.asm"
		include "Objects/Bosses/Mecha Sonic/MicroBullet.asm"
		include "Objects/Bosses/Mecha Sonic/Spark.asm"
		include "Objects/Bosses/Mecha Sonic/Monologue/Code.asm"
		include "Objects/Bosses/Mecha Sonic/Monologue/Code2.asm"
		include "Objects/Bosses/Arthur/Code.asm"
		include "Objects/Bosses/Arthur/Spear.asm"
		include "Objects/Bosses/Arthur/ArmorShards.asm"
		include "Objects/Bosses/Arthur/Firebomb.asm"
		include "Objects/Bosses/Arthur/Flame.asm"
		include "Objects/Bosses/Arthur/Axe.asm"
		include "Objects/Bosses/Gloamglozer/Code.asm"
		include "Objects/Bosses/Gloamglozer/Dialogue.asm"
		include "Objects/Bosses/Gloamglozer/Prin Prin.asm"
		include "Objects/Bosses/Gloamglozer/SharpThingy.asm"
		include "Objects/Bosses/Gloamglozer/Bloodeau.asm"
		include "Objects/Bosses/Gloamglozer/Mickey.asm"
		include "Objects/Bosses/Gloamglozer/Hellgirl.asm"
		include "Objects/Bosses/Gloamglozer/LoveBullet.asm"
		include "Objects/Bosses/Gloamglozer/Chesire.asm"
		include "Objects/Bosses/Gloamglozer/ChesireLock.asm"
		include "Objects/Bosses/Gloamglozer/SCZ1 Cutscene.asm"
		include "Objects/Bosses/Eggman/Code.asm"
		include "Objects/Bosses/Gluttony/Code.asm"
		include "Objects/Bosses/Astaroth/Code.asm"
		include "Objects/Bosses/The Soulless One/Code.asm"
		include "Objects/Bosses/Headliss/Code.asm"
		include "Objects/Bosses/Headliss/Axt.asm"
		include "Objects/Bosses/Headliss/Segment.asm"
		include "Objects/Feal/Code2.asm"
		include "Objects/Bosses/Scientist/Code.asm"
		include "Objects/Bosses/Great Axe Lord/Boss.asm"
		include "Objects/Bosses/Great Blue Lord/Boss.asm"
		include "Objects/Bosses/Shaft/Shaft.asm"
		include "Objects/Bosses/Shielder/Boss.asm"
		include "Objects/Bosses/Shaft2/Shaft.asm"
		include "Objects/Bosses/Cerberus/Boss.asm"
		include "Objects/Bosses/Shaft(Mecha)/Shaft.asm"
		include "Objects/Bosses/Werewolf/Code.asm"
		include "Objects/Bosses/Centipede/Code.asm"
		include "Objects/Bosses/Dark Priest Shaft/Code.asm"
		include "Objects/Bosses/Dark Priest Shaft/Code2.asm"
		include "Objects/Magic Skull/Code.asm"
		include "Objects/GMZ1Lava/Code.asm"
		include "Objects/BlackStretch/Code.asm"
		include "Objects/Bosses/Evil Eye/Code.asm"
		include "Objects/Bosses/Evil Eye/Process.asm"
		include "Objects/Foreground Plant/Foreground Plant.asm"
		include "Objects/FDZ3Warper/Code.asm"
		include "Objects/Archer Armor/Code.asm"
		include "Objects/Orbinaut Armor/Code.asm"
		include "Objects/Archer Armor/Code2.asm"
		include "Objects/Bosses/Death X/Code.asm"
		include "Objects/Phantom Hand/Code.asm"
		include "Objects/Bosses/Fire Head/Boss.asm"
		include "Objects/Bosses/The Heartless One/Code.asm"
		include "Objects/Red Guardian/Code.asm"
		include "Objects/Killer Fish/Code.asm"

		include "Objects/Bosses/Grim Reaper/Boss.asm"
		include "Objects/Bosses/TwoFaces/Boss.asm"
