; =========; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 01 2019 20:31:37 GMT+0200 (FLE Standard Time)
; ================================================================================

Map_FloatingPlatformMGZ1:
		dc.w Map_FloatingPlatformMGZ1_2-Map_FloatingPlatformMGZ1
Map_FloatingPlatformMGZ1_2:	dc.b 0, 8
		dc.b $F0, $F, 1, $52, $FF, $E0	
		dc.b $F0, 3, 1, $62, 0, 0	
		dc.b $F0, 1, 1, $66, 0, 8	
		dc.b 0, 1, 1, $66, 0, 8	
		dc.b $F0, 1, 1, $68, 0, $10	
		dc.b 0, 1, 1, $68, 0, $10	
		dc.b $F0, 1, 1, $6B, 0, $18	
		dc.b 0, 1, 1, $6B, 0, $18	
		even