; ===========================================================================
; ---------------------------------------------------------------------------
; Pattern addresses for left V-scroll column sprites (generated by "FixVSprites.exe")
; ---------------------------------------------------------------------------

DDZ_VSF_Patterns:
		dc.w	$08A0
		dc.w	DDZ_VSF_00-(DDZ_VSF_Patterns+2)
		dc.w	DDZ_VSF_01-(DDZ_VSF_Patterns+2)
		dc.w	DDZ_VSF_02-(DDZ_VSF_Patterns+2)
		dc.w	DDZ_VSF_03-(DDZ_VSF_Patterns+2)

DDZ_VSF_00:	dc.w	$4001,$4009,$4010,$4018,$4020,$4023,$C02B,$C02F
DDZ_VSF_01:	dc.w	$4037,$403F,$4047,$404F,$4057,$405A,$C062,$C066
DDZ_VSF_02:	dc.w	$406E,$4076,$407E,$4086,$4037,$408E,$C02B,$C096
DDZ_VSF_03:	dc.w	$409E,$40A5,$40AD,$40B5,$40BD,$40C0,$C062,$C0C8

; ===========================================================================
